name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.4
      with:
        upload_translations: true
        download_translations: true
      env:
        GITHUB_TOKEN: $
        CROWDIN_PROJECT_ID: $RKTM
        CROWDIN_PERSONAL_TOKEN: $d1efc11a45f7848a28ac629b3c8c3083
